name: Eleventy Build


on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master


        - name: Setup Node
          uses: actions/setup-node@v4.0.3
          with:
            node-version: 'latest'


        - run: npm ci
        - run: npm run build


        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            deploy_key: ${{ secrets.ELEVENTY }}
            publish_dir: ./dist